### PR TITLE
fix syncing utimes if copied files

### LINKED ISSUE #257: Does not work with grunt-newer due to the timestamp precision disagreement
As I tried, when specify newer:copy, the files will be copied no matter whether it gets modified. As I have observed, grunt-contrib-copy uses `fs.utimesSync(dest, stat.atime, stat.mtime);` to sync the timestamp, which only gives second-level precision (can be reproduced by first using grunt-contrib-copy to copy the file and then stat the original file and the copied version to see). And I think grunt-newer uses more strict comparison which based on the millisecond-level precision. I don't know this should be either a bug or a feature enhancement for either package, but it would be great if they can work together.

### PR DESCRIPTION
**Pull request by nalajcie**
`fs.utimesSync` saves times with one second precision, while `fs.statSync` gives us microsecond precision.

This makes `utimes` not synchronized on filesystems with sub-second `atime`/`ctime`/`mtime` precision.

Upgraded to use newer `fs.futimesSync` interface providing correct precision.

Fixes #257.

### CODE REVIEW

**Comment by XhmikosR** [comment]
Doesn't seem to work on Windows.

```

> grunt-contrib-copy@0.8.2 test C:\Users\xmr\Desktop\grunt\grunt-contrib-copy
> grunt test

Running "jshint:all" (jshint) task
>> 3 files lint free.

Running "clean:test" (clean) task
>> 1 path cleaned.

Running "copy:main" (copy) task
Warning: EPERM: operation not permitted, futime Use --force to continue.

Aborted due to warnings.
npm ERR! Test failed.  See above for more details.

C:\Users\xmr\Desktop\grunt\grunt-contrib-copy>
```

**Comment by nalajcie** [comment]
Fixed file open mode for windows platform (it requires 'r+' mode to be able to change utimes, linux requires dirs to be opened with 'r' only).

Unfortunately, the tests will not work on windows platform:
 - chmod on windows is not working as expected (detailed comment in the source: https://github.com/nodejs/node/blob/master/deps/uv/src/win/fs.c#L1064) - probably the test should be disabled or changed to be less restrictive on windows platform
 - timestamp will not have sub-second precision due to bug in nodejs (issue: https://github.com/nodejs/node/issues/2069)

**Comment by XhmikosR** [comment]
We could skip the test on Windows as long as things work even without the subsecond precision.

File: tasks/copy.js [hunk 1]
```diff
@@ -14,6 +14,7 @@ module.exports = function(grunt) {
   var fs = require('fs');
   var chalk = require('chalk');
   var fileSyncCmp = require('file-sync-cmp');
+  var isWindows = /^win/.test(process.platform);
```
Comment (sindresorhus) [inline tasks/copy.js]: Should be: `var isWindows = process.platform === 'win32';` And yes, it's win32 for 64-bit too.

**Comment by XhmikosR** [comment]
@shama @vladikoff: any ideas how we should proceed with this?

**Comment by shama** [comment]
I'm good with skipping that test on Windows for now and merging this.

**Comment by XhmikosR** [comment]
@nalajcie: can you rebase and squash the patches?

**Comment by XhmikosR** [comment]
Thanks!

**Comment by krnlde** [comment]
So the issue on windows will persist?

**Comment by shama** [comment]
@krnlde This is an issue with our testing on Windows. Are you running into a syncing utime issue on Windows?

**Comment by krnlde** [comment]
Yes. I updated to 1.0.0 today but that didn't help. There are also a few tickets in grunt newer. They are not sure where it comes from. And so am I.

**Comment by tschaub** [comment]
@krnlde if you can provide a repo that includes the minimum needed to reproduce your problem, that would be helpful.  I tried https://github.com/giovannipds/grunt-newer-copy-test and this works as expected on OS X with `grunt-contrib-copy@0.8.2`.  I'd be interested to know if others can reproduce the problem with that repo outside Windows.  It would also be good to know if the changes in `grunt-contrib-copy@1.0.0` make a difference on Windows.

**Comment by krnlde** [comment]
Hey @tschaub sorry I missed your response. As stated in https://github.com/tschaub/grunt-newer/issues/86 it should not be possible to reproduce this outside Windows. They implemented a `tolerance` option to workaround this problem, but a definitive solution would of course be better.

Regarding the repo to reproduce the behaviour (on Windows): we are using it in https://github.com/micromata/bootstrap-kickstart . Unfortunately this is not the *minimum needed setup* you requested. But I don't have time to create one right now. Does this work for you anyway?

**Comment by simevo** [comment]
Hi, while testing this module as part of the debian packaging effort, we noticed timestamp failures on i386 and armhf architectures. This is on:
- Linux with kernel 4.9.0
- ext4 filesystem
- nodejs v4.8.2
For more details see: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=861515
Is there anything we should try to pinpoint the issue ?

**Comment by XhmikosR** [comment]
@simevo: the issue shouldn't happen in the latest release. So if it still happens, there must be a difference in how the OS handles times. The main change in this PR is https://github.com/gruntjs/grunt-contrib-copy/pull/268/commits/217819f9625b19589c417905faf8532aa479e083#diff-951068604e1c942635e6a1f96a88994dL122

**Comment by simevo** [comment]
We're on grunt-contrib-copy v1.0.0 and we have the commit you mention. I have reproduced the issue on a i386 lxc container running debian sid within a amd64 debian host running strecth, as follows:
```
apt install wget xz-utils git
cd /opt
wget https://nodejs.org/download/release/v4.8.2/node-v4.8.2-linux-x86.tar.xz
xz -d node-v4.8.2-linux-x86.tar.xz
tar xf node-v4.8.2-linux-x86.tar
rm node-v4.8.2-linux-x86.tar
echo 'export PATH=/opt/node-v4.8.2-linux-x86/bin:$PATH' >> ~/.bashrc
source ~/.bashrc
cd
git clone https://github.com/gruntjs/grunt-contrib-copy.git
cd grunt-contrib-copy
npm install grunt chalk file-sync-cmp jshint grunt-contrib-jshint grunt-contrib-clean grunt-contrib-nodeunit grunt-contrib-internal
grunt test
```

this is what I get:
```
Running "nodeunit:tests" (nodeunit) task
Testing copy_test.js.......F.
>> copy - timestampEqual
>> Error: 1493719861389 == 1493719861494
>>   at Object.exports.copy.timestampEqual (test/copy_test.js:92:10)
>>   at processImmediate [as _immediateCallback] (timers.js:396:17)

>> copy - timestampEqual
>> Error: 1493719861389 == 1493719861494
>>   at Object.exports.copy.timestampEqual (test/copy_test.js:93:10)
>>   at processImmediate [as _immediateCallback] (timers.js:396:17)

Warning: 2/17 assertions failed (19ms) Use --force to continue.
```
```

**Comment by XhmikosR** [comment]
What happens with a newer node version?

**Comment by simevo** [comment]
```
node -v
v6.10.2
```
I tear down the grunt-contrib-copy dir and pull everything again, then `node_modules/grunt/bin/grunt test` returns:
```
...
Running "nodeunit:tests" (nodeunit) task
Testing copy_test.js.......F.
>> copy - timestampEqual
>> Error: 1493723278009 == 1493723278082
>>   at Object.timestampEqual (test/copy_test.js:92:10)
>>   at runCallback (timers.js:666:20)
>>   at tryOnImmediate (timers.js:639:5)
>>   at processImmediate [as _immediateCallback] (timers.js:611:5)

>> copy - timestampEqual
>> Error: 1493723278009 == 1493723278082
>>   at Object.timestampEqual (test/copy_test.js:93:10)
>>   at runCallback (timers.js:666:20)
>>   at tryOnImmediate (timers.js:639:5)
>>   at processImmediate [as _immediateCallback] (timers.js:611:5)

Warning: 2/17 assertions failed (19ms) Use --force to continue.
```

**Comment by XhmikosR** [comment]
Then only the OS is left as a variable here. Not sure what else can be done.

**Comment by simevo** [comment]
To make sure it's not an artifact of lxc or a side-effect of mixing amd64 host (and kernel) with i386 libc &C, I set up an i386 VirtualBox clone. It is reproducible there too. Should I open an issue on this ?

**Comment by XhmikosR** [comment]
If it's something you can consistently reproduce with a clean OS which is the latest stable version, then sure. Weird that Travis CI is passing though.

**Comment by simevo** [comment]
done ! travis is running on `arch: "amd64"` (64-bit), we're seeing this on i386 (32-bit)
